language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  
install: "pip install cryptography"

install:
  - pip install cryptography unittest2 coveralls
  
script:
  - nosetests --exe --all-modules --with-coverage --cover-package=x509Validation
  
after_success:
    - coveralls
